# Site settings
title: 清华大学化学系科协
SEOTitle: 清化科协
header-img: img/home-bg.jpg
email: thuchemst@163.com
description: 
keyword: 
url: "https://thuchemst.github.io"              # your host, for absolute URL
baseurl: ""          # for example, '/blog' if your blog hosted on 'host/blog'





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: 
# Google Analytics
# ga_track_id: ''            # Format: UA-xxxxxx-xx
# ga_domain: 



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: 
sidebar-avatar:       # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Links
link: [
    {
        title: "清华大学化学系",
        href: "http://www.chem.tsinghua.edu.cn"
    },{ 
        title: "",
        href: ""
    },{
        title: "Reaxys",
        href: "https://www.reaxys.com/reaxys/secured/start.do"
    },{ 
        title: "SciFinder",
        href: "https://scifinder.cas.org/scifinder"
    },{
        title: "<I>i</I>BonD 键能数据库",
        href: "http://202.113.231.233"
    },{ 
        title: "",
        href: ""
    },{
        title: "Nature",
        href: "http://www.nature.com/nature/current_issue.html"
    },{
        title: "Science",
        href: "http://science.sciencemag.org"
    },{
        title: "ACS Publication",
        href: "http://pubs.acs.com"
    },{
        title: "Royal Society of Chemistry",
        href: "http://pubs.rsc.org/en/journals"
    },{
        title: "Organic Chemistry Journals",
        href: "http://www-jmg.ch.cam.ac.uk/data/c2k/cj/organic.html"
    },{
        title: "",
        href: ""
    },{
        title: "Sci-Hub",
        href: "http://www.sci-hub.cc"
    },{
        title: "Library Genesis",
        href: "http://gen.lib.rus.ec"
    },{
        title: "Chemistry Reference Resolver",
        href: "http://chemsearch.kovsky.net"
    }]



# Resources
software: [
        {
          title: "ChemOffice 15.1 win",
		  href-in: "Software/ChemOffice/ChemOffice 15.1 WIN.zip",
          href: "http://pan.baidu.com/s/1miB7Sso",
          code: 4z9d
        },{
          title: "ChemDraw 15.0 mac",
		  href-in: "Software/ChemOffice/ChemDraw 15.0 OSX.zip",
          href: "http://pan.baidu.com/s/1geEjFRt",
          code: nyyf
        },{
          title: "Gaussian09 D.01 lnx",
		  href-in: "Software/Gaussian/G09L-D01.zip",
          href: "http://pan.baidu.com/s/1i4QVVtN",
          code: ksuc
        },{
          title: "Gaussian09 D.01 win",
		  href-in: "Software/Gaussian/G09W-D01-32bit.zip",
          href: "http://pan.baidu.com/s/1c23FMgS",
          code: wnn4
        },{
          title: "Gaussian09 D.01 mac (with gview)",
          href-in: "Software/Gaussian/G09IM-D01.zip",
        },{
          title: "GaussView 5.0.9 win",
		  href-in: "Software/Gaussian/GaussianView 5.0.9_win.zip",
          href: "http://pan.baidu.com/s/1hr7vjlM",
          code: 6tg8
        },{
          title: "GaussView 5.0.9 lnx",
		  href-in: "Software/Gaussian/GaussianView 5.0.9_linux.zip",
          href: "http://pan.baidu.com/s/1kUBYJiR",
          code: vbhf
        },{
          title: "Materials Studio 8.0 win",
		  href-in: "Software/Materials Studio/Materials_Studio 8.0 WIN.zip",
          href: "http://pan.baidu.com/s/1i4IPsS9",
          code: g3k3
        },{
          title: "MestReNova 9.0 win",
		  href-in: "Software/Mestrenova/MestReNova 9.0 WIN.zip",
          href: "http://pan.baidu.com/s/1kVhhGLD",
          code: bzdx
        },{
          title: "MestReNova 10.0 mac",
		  href-in: "Software/Mestrenova/MestReNova 10.0 OSX.zip",
          href: "http://pan.baidu.com/s/1i5nr0ep",
          code: kr4g
        },{
          title: "MOE 2015 mac",
		  href-in: "Software/MOE/MOE2015.zip",
        },]

